################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_bootload.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_core.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_main.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_parse.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_reset.c 

OBJS += \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_bootload.o \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_core.o \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_main.o \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_parse.o \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_reset.o 

C_DEPS += \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_bootload.d \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_core.d \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_main.d \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_parse.d \
./gecko_sdk_4.5.0/platform/bootloader/core/btl_reset.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.5.0/platform/bootloader/core/btl_bootload.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_bootload.c gecko_sdk_4.5.0/platform/bootloader/core/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBTL_SPI_USART_ENABLE=1' '-DBOOTLOADER_SUPPORT_EXTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/driver" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/storage/spiflash_sfdp" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/bootloader/core/btl_bootload.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/bootloader/core/btl_core.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_core.c gecko_sdk_4.5.0/platform/bootloader/core/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBTL_SPI_USART_ENABLE=1' '-DBOOTLOADER_SUPPORT_EXTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/driver" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/storage/spiflash_sfdp" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/bootloader/core/btl_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/bootloader/core/btl_main.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_main.c gecko_sdk_4.5.0/platform/bootloader/core/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBTL_SPI_USART_ENABLE=1' '-DBOOTLOADER_SUPPORT_EXTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/driver" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/storage/spiflash_sfdp" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/bootloader/core/btl_main.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/bootloader/core/btl_parse.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_parse.c gecko_sdk_4.5.0/platform/bootloader/core/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBTL_SPI_USART_ENABLE=1' '-DBOOTLOADER_SUPPORT_EXTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/driver" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/storage/spiflash_sfdp" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/bootloader/core/btl_parse.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/bootloader/core/btl_reset.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/bootloader/core/btl_reset.c gecko_sdk_4.5.0/platform/bootloader/core/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBTL_SPI_USART_ENABLE=1' '-DBOOTLOADER_SUPPORT_EXTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader-storage-spiflash-sfdp-single_IWSB/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/driver" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/storage/spiflash_sfdp" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/bootloader/core/btl_reset.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


