################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_acmp.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_adc.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cmu.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_core.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cryotimer.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_crypto.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_csen.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_dbg.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_emu.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpcrc.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpio.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_i2c.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_idac.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_ldma.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lesense.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_letimer.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_leuart.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_msc.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_opamp.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_pcnt.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_prs.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rmu.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rtcc.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_system.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_timer.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_usart.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_vdac.c \
/home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_wdog.c 

OBJS += \
./gecko_sdk_4.5.0/platform/emlib/src/em_acmp.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_adc.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_core.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_cryotimer.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_crypto.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_csen.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_dbg.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_emu.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_gpcrc.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_i2c.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_idac.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_lesense.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_letimer.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_leuart.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_msc.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_opamp.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_pcnt.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_prs.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_rmu.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_rtcc.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_system.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_timer.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_usart.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_vdac.o \
./gecko_sdk_4.5.0/platform/emlib/src/em_wdog.o 

C_DEPS += \
./gecko_sdk_4.5.0/platform/emlib/src/em_acmp.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_adc.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_core.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_cryotimer.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_crypto.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_csen.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_dbg.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_emu.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_gpcrc.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_i2c.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_idac.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_lesense.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_letimer.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_leuart.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_msc.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_opamp.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_pcnt.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_prs.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_rmu.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_rtcc.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_system.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_timer.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_usart.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_vdac.d \
./gecko_sdk_4.5.0/platform/emlib/src/em_wdog.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.5.0/platform/emlib/src/em_acmp.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_acmp.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_acmp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_adc.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_adc.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_adc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_cmu.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cmu.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_core.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_core.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_cryotimer.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_cryotimer.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_cryotimer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_crypto.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_crypto.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_crypto.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_csen.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_csen.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_csen.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_dbg.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_dbg.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_dbg.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_emu.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_emu.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_gpcrc.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpcrc.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_gpcrc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_gpio.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_gpio.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_i2c.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_i2c.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_idac.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_idac.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_idac.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_ldma.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_ldma.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_lesense.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_lesense.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_lesense.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_letimer.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_letimer.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_letimer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_leuart.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_leuart.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_leuart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_msc.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_msc.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_opamp.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_opamp.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_opamp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_pcnt.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_pcnt.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_pcnt.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_prs.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_prs.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_prs.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_rmu.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rmu.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_rmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_rtcc.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_rtcc.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_rtcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_system.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_system.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_timer.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_timer.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_usart.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_usart.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_vdac.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_vdac.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_vdac.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.5.0/platform/emlib/src/em_wdog.o: /home/lmh/SimplicityStudio/SDKs/gecko_sdk/platform/emlib/src/em_wdog.c gecko_sdk_4.5.0/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DEFR32FG12P433F1024GL125=1' '-DBTL_PARSER_SUPPORT_CUSTOM_TAGS=1' '-DBTL_PARSER_SUPPORT_LZMA=1' '-D_LZMA_SIZE_OPT=1' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DSL_BOARD_NAME="BRD4253A"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_915=1' '-DHARDWARE_BOARD_SUPPORTS_2_RF_BANDS=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_915=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/config" -I"/home/lmh/SimplicityStudio/v5_workspace/bootloader_ota_cubesat/autogen" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32FG12P/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser/compression" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/debug" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/parser" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/api" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/core/flash" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/bootloader/security" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/include" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/third_party/mbedtls/library" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"/home/lmh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.5.0/platform/emlib/src/em_wdog.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


